[workspace]
members = ["crates/*"]
exclude = ["examples"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Levi Bland <levi@arcane.fi>"]
repository = "https://github.com/arcane-fi/jutsu"
rust-version = "1.82"

[workspace.dependencies]
borsh = { version = "1.5", features = ["derive"] }
bytemuck = "1.21.0"
pinocchio = "0.9.2"
pinocchio-pubkey = "0.3"
pinocchio-system = "0.3"
sha2 = "0.10"
quote = "1.0"
proc-macro2 = "1.0"
syn = "2.0"
jutsu = { path = "crates/lib" }
jutsu-accounts = { path = "crates/accounts" }
jutsu-discriminator = { path = "crates/discriminator" }
jutsu-discriminator-derive = { path = "crates/discriminator-derive" }
jutsu-syn = { path = "crates/syn" }
jutsu-errors = { path = "crates/errors" }
jutsu-errors-derive = { path = "crates/errors-derive" }
jutsu-pda = { path = "crates/pda" }
jutsu-utility = { path = "crates/utility" }
jutsu-context = { path = "crates/context" }
jutsu-ser = { path = "crates/ser" }
jutsu-instruction-attribute-macro = { path = "crates/instruction-attribute-macro" }