[package]
name = "jutsu-accounts"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
pinocchio.workspace = true
pinocchio-system.workspace = true
jutsu-errors.workspace = true
jutsu-utility.workspace = true
jutsu-ser.workspace = true