[package]
name = "hayabusa-pda"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Hayabusa PDA"

[dependencies]
pinocchio.workspace = true
hayabusa-errors.workspace = true