[package]
name = "hayabusa-errors"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Hayabusa errors"

[dependencies]
pinocchio.workspace = true